export const data2Render = {
    name:'Name',
    title:'Title',
    phone:'Phone',
    email:'Email',
    contactNotes:'Contact Notes',
    remarksSection:'Remarks Section',
    accountCode:'Account Code',
    accountName:'Account Name',
    salesRep: 'Sales Rep',
    category: 'Category',
    subcategory: 'Sub Category',
    localPledge: 'Local Pledge',
    billTo:'Bill to',
    shipTo:'Ship to',
    deliveryNotes:'Delivery Notes',
    orderNotes:'Order notes',
    lastOrder:'Last order',
    routeNumbers:'Route Numbers',
    noDeliveryDays:'No Delivery Days',
    stopNumber:'Stop Number',
    transportationdeliveryNotes:'Delivery Notes',
    avgDeliveryTime:'Avg Delivery Time',
    deliveryWindow:'Delivery Window',
    driversName:'Drivers Name',
    remarksSections:'Remarks',
}